name: build

on: [ push, pull_request ]

jobs:
  build:
    #run if push or pull_requests from fork
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          architecture: x64
          distribution: adopt
          cache: maven

      - name: Package
        run: mvn --batch-mode --update-snapshots checkstyle:checkstyle