name: build

on: [ push, pull_request ]

jobs:
  build:
    #run if push or pull_requests from fork
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java: [17]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          architecture: x64
          distribution: adopt
          cache: maven

      - name: Test
        run: mvn --batch-mode --update-snapshots tests -Dmatsim.preferLocalDtds=true -Dmaven.javadoc.skip -e
      - uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: reports/jacoco/

    env:
      MAVEN_OPTS: -Xmx10G